insert  into track (name, album,  duration) VALUES ('Natural blues', 'Hotel Ambient',  356);
insert  into track (name, album,  duration) VALUES ('Track2', 'Hotel Ambient',  226);
insert  into track (name, album,  duration) VALUES ('Track3', 'Left',  12);
insert  into track (name, album,  duration) VALUES ('Track4', 'Right',  356);
insert  into track (name, album,  duration) VALUES ('Track5', 'Down', 35);
insert  into track (name, album,  duration) VALUES ('Track6', 'Fly', 35);
insert  into track (name, album,  duration) VALUES ('Track7', 'Light', 45);
insert  into track (name, album,  duration) VALUES ('Track8', 'Left', 55);
insert  into track (name, album,  duration) VALUES ('Track9', 'Hotel Ambient', 15);
insert  into track (name, album,  duration) VALUES ('Track10', 'Down', 25);
insert into artist_track (track_id, artist_id) values (1,2);
insert into artist_track (track_id, artist_id) values (1,3);
insert into artist_track (track_id, artist_id) values (2,1);
insert into artist_track (track_id, artist_id) values (2,5);
insert into artist_track (track_id, artist_id) values (3,6);
insert into artist_track (track_id, artist_id) values (4,1);
insert into artist_track (track_id, artist_id) values (5,3);
insert into artist_track (track_id, artist_id) values (6,5);
insert into artist_track (track_id, artist_id) values (7,4);
insert into artist_track (track_id, artist_id) values (8,6);
insert into artist_track (track_id, artist_id) values (9,2);
insert into artist_track (track_id, artist_id) values (10,6);
insert into genre_track (track_id, genre_id) values (1, 2);
insert into genre_track (track_id, genre_id) values (2, 5);
insert into genre_track (track_id, genre_id) values (3, 4);
insert into genre_track (track_id, genre_id) values (4, 1);
insert into genre_track (track_id, genre_id) values (5, 3);
insert into genre_track (track_id, genre_id) values (6, 4);
insert into genre_track (track_id, genre_id) values (7, 6);
insert into genre_track (track_id, genre_id) values (8, 2);
insert into genre_track (track_id, genre_id) values (9, 4);
insert into genre_track (track_id, genre_id) values (10, 3);
insert into genre_track (track_id, genre_id) values (1, 1);
insert into genre_track (track_id, genre_id) values (5, 4);
insert into genre_track (track_id, genre_id) values (5, 6);
insert into genre_track (track_id, genre_id) values (7, 2);
insert into genre (name, rating) values ('Rock', 1);
insert into genre (name, rating) values ('Rap', 2);
insert into genre (name, rating) values ('Blues', 4);
insert into genre (name, rating) values ('Country', 3);
insert into genre (name, rating) values ('Classic', 6);
insert into genre (name, rating) values ('Jazz', 8);
insert into artist (name, age) values ('John', 25);
insert into artist (name, age) values ('Bob', 22);
insert into artist (name, age) values ('Ana', 31);
insert into artist (name, age) values ('Lil', 18);
insert into artist (name, age) values ('Peter', 27);
insert into artist (name, age) values ('Dager', 42);